name: MegaTroll
author: Sean_M
version: "1.0.0"
api: [1.0.0]
description: Troll
main: Sean_M\MegaTroll\Main

commands:
    troll:
        description: "Troll a player."
        usage: "/troll [player] op - Sends a fake op message to a player.\nMore soon!"
        permission: megatroll.troll
